export function buildStatePayloadShape({
  subjects = [],
  documents = [],
  apuntes = [],
  expedientes = [],
  exdocs = [],
  documentos = [],
  annotations = [],
  favorites = [],
  mmExpanded = [],
  state = {},
  mmPos = {},
  centerLabel = ''
}) {
  return {
    subjects: subjects.filter((s) => String(s.id) !== '__shared__'),
    documents: documents.filter((d) => !d.shared),
    apuntes: apuntes.filter((x) => !x.sharedDoc),
    expedientes: expedientes.filter((e) => !e.shared),
    exdocs: exdocs.filter((x) => !x.shared),
    documentos: documentos.filter((x) => !x.sharedDoc),
    annotations: annotations.filter((a) => !a.shared),
    favorites: [...favorites],
    docOrder: state.docOrder || [],
    readingLists: state.readingLists || [],
    mmPos,
    centerLabel,
    mmExpanded: [...mmExpanded],
    annOrder: state.annOrder || {},
    bookPos: state.bookPos || {},
    flashcards: state.flashcards || [],
    importedPacks: state.importedPacks || [],
    streak: state.streak,
    studyMax: state.studyMax,
    mazos: state.mazos || [],
    seenSwipeTip: state.seenSwipeTip,
    sessions: state.sessions || [],
    goal: state.goal,
    bookmarks: state.bookmarks || {},
    lastScroll: state.lastScroll || {}
  };
}

export function makeFreshStateSnapshot() {
  return {
    favorites: new Set(),
    mmExpanded: new Set(),
    docOrder: [],
    readingLists: [],
    flashcards: [],
    sessions: [],
    bookmarks: {},
    lastScroll: {},
    annOrder: {},
    bookPos: {},
    recordatorios: [],
    todos: [],
    copias: [],
    papelera: [],
    hiddenBooks: [],
    tabs: [],
    tabActive: null,
    colaboradores: [],
    redaccionDraft: null,
    lastOpened: null,
    users: [],
    perfilAbogado: { nombre: '', rut: '', domicilio: '', email: '', cargo: 'Abogado' },
    membrete: { logo: '', pie: '' },
    compareceTpl: null,
    causaTpl: null,
    materias: null,
    rolesProcesales: null,
    indivTpl: null,
    tribTipos: null
  };
}
